---
title: "EDA_plots"
author: "LOO JIA HAO (17218692)"
date: "5/27/2021"
output: pdf_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse) 
library(ggcorrplot)
library(ggplot2)
library(cowplot)

df <- read.csv("WA_Fn-UseC_-Telco-Customer-Churn.csv", stringsAsFactors = TRUE)

theme_bar <- theme_bw() +
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        legend.position='none')

theme_bar2 <- theme_bw() +
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_blank(),
        axis.text = element_text(size = 10),
        legend.position='none')

theme_pie <- theme_void() +
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        axis.text = element_text(size = 12),
        legend.position='none')

theme_donut <- theme_void() +
  theme(plot.title = element_text(size = 12, hjust = 0.5),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position='none')
        
# '#F8766D', '#00BA38', '#619CFF'

```


```{r}
df$SeniorCitizen <- as.factor(ifelse(df$SeniorCitizen==1, 'Yes', 'No'))

glimpse(df)
```


```{r fig.width = 8}
df_churn <- df %>%
  group_by(Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100) %>%
  mutate(Pos = cumsum(Percent)-(Percent/2))

# Churn Distribution (Bar Chart)
p1 <- ggplot(df_churn, aes(Churn, Count), fill = Churn) +
  geom_col(fill = c('#F8766D', '#00BA38')) +
  geom_text(aes(label = Count), vjust = -0.2) +
  ggtitle("Churn Distribution") +
  theme_bar


# Churn Rate (Pie Chart)
p2 <- ggplot(df_churn, aes(x = '', y = Percent, fill = Churn)) +
  geom_col(fill = c('#F8766D', '#00BA38')) +
  geom_text(label = sprintf("%.2f%%", df_churn$Percent),
            position = position_stack(vjust = 0.5, reverse = TRUE)) +
  scale_y_continuous(breaks = df_churn$Pos,
                     labels = df_churn$Churn) +
  coord_polar('y') +
  ggtitle("Churn Rate") +
  theme_pie

plot_grid(p1, p2)

```


```{r fig.width = 8}
# Gender plot
df_gender <- df %>%
  group_by(gender, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p3 <- ggplot(df_gender, aes(x = gender, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('Gender') +
    theme_bar2
    
p4 <- df_gender %>%
  filter(gender=='Female') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Female") +
    theme_donut

p5 <- df_gender %>%
  filter(gender=='Male') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Male") +
    theme_donut


p_gender <- plot_grid(p3, plot_grid(p4, p5, ncol = 1))

# Age Range plot
df_age <- df %>%
  group_by(SeniorCitizen, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p6 <- ggplot(df_age, aes(x = SeniorCitizen, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('SeniorCitizen') +
    theme_bar2

    
p7 <- df_age %>%
  filter(SeniorCitizen=='No') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No") +
    theme_donut

p8 <- df_age %>%
  filter(SeniorCitizen=='Yes') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Yes") +
    theme_donut


p_age <- plot_grid(p6, plot_grid(p7, p8, ncol = 1))

# Partner plot
df_partner <- df %>%
  group_by(Partner, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p9 <- ggplot(df_partner, aes(x = Partner, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('Partner') +
    theme_bar2

    
p10 <- df_partner %>%
  filter(Partner=='No') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No") +
    theme_donut

p11 <- df_partner %>%
  filter(Partner=='Yes') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Yes") +
    theme_donut


p_partner <- plot_grid(p9, plot_grid(p10, p11, ncol = 1))

# Dependent Plot
df_dependent <- df %>%
  group_by(Dependents, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p12 <- ggplot(df_dependent, aes(x = Dependents, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('Dependents') +
    theme_bar2

    
p13 <- df_dependent %>%
  filter(Dependents=='No') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No") +
    theme_donut

p14 <- df_dependent %>%
  filter(Dependents=='Yes') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Yes") +
    theme_donut


p_dependent <- plot_grid(p12, plot_grid(p13, p14, ncol = 1))


plot_grid(plot_grid(p_gender, p_age, p_partner, p_dependent, ncol = 2),
          get_legend(p12 + theme(legend.position='right')),
          ncol = 2,
          rel_widths = c(2, 0.25))

```


```{r fig.width = 10}
# Phone Service plot
df_phone <- df %>%
  group_by(PhoneService, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p15 <- ggplot(df_phone, aes(x = PhoneService, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('PhoneService') +
    theme_bar2

    
p16 <- df_phone %>%
  filter(PhoneService=='No') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No") +
    theme_donut

p17 <- df_phone %>%
  filter(PhoneService=='Yes') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Yes") +
    theme_donut

p_phone <- plot_grid(p15,
                     plot_grid(p16, p17, ncol = 3),
                     ncol = 2,
                     rel_widths = c(1.5, 2))

# Mulitple Lines plot
df_lines <- df %>%
  group_by(MultipleLines, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p18 <- ggplot(df_lines, aes(x = MultipleLines, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('MultipleLines') +
    theme_bar2

    
p19 <- df_lines %>%
  filter(MultipleLines=='No') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No") +
    theme_donut

p20 <- df_lines %>%
  filter(MultipleLines=='No phone service') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No phone service") +
    theme_donut

p21 <- df_lines %>%
  filter(MultipleLines=='Yes') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Yes") +
    theme_donut


p_lines <- plot_grid(p18,
                     plot_grid(p19, p20, p21, ncol = 3),
                     ncol = 2,
                     rel_widths = c(1.5, 2))

# Internet Service plot
df_internet <- df %>%
  group_by(InternetService, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p22 <- ggplot(df_internet, aes(x = InternetService, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('InternetService') +
    theme_bar2

    
p23 <- df_internet %>%
  filter(InternetService=='DSL') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("DSL") +
    theme_donut

p24 <- df_internet %>%
  filter(InternetService=='Fiber optic') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Fiber optic") +
    theme_donut

p25 <- df_internet %>%
  filter(InternetService=='No') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No") +
    theme_donut


p_internet <- plot_grid(p22,
                        plot_grid(p23, p24, p25, ncol = 3),
                        ncol = 2,
                        rel_widths = c(1.5, 2))

plot_grid(p_phone, p_lines, p_internet,
          get_legend(p15 + theme(legend.position='bottom')),
          ncol = 1)

```


```{r fig.width=10}
# Online Security plot
df_security <- df %>%
  group_by(OnlineSecurity, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p26 <- ggplot(df_security, aes(x = OnlineSecurity, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('OnlineSecurity') +
    theme_bar2

    
p27 <- df_security %>%
  filter(OnlineSecurity=='No') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No") +
    theme_donut

p28 <- df_security %>%
  filter(OnlineSecurity=='No internet service') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No internet service") +
    theme_donut

p29 <- df_security %>%
  filter(OnlineSecurity=='Yes') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Yes") +
    theme_donut


p_security <- plot_grid(p26,
                        plot_grid(p27, p28, p29, ncol = 3),
                        ncol = 2,
                        rel_widths = c(1.5, 2))

# Online backup plot
df_backup <- df %>%
  group_by(OnlineBackup, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p30 <- ggplot(df_backup, aes(x = OnlineBackup, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('OnlineBackup') +
    theme_bar2

    
p31 <- df_backup %>%
  filter(OnlineBackup=='No') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No") +
    theme_donut

p32 <- df_backup %>%
  filter(OnlineBackup=='No internet service') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No internet service") +
    theme_donut

p33 <- df_backup %>%
  filter(OnlineBackup=='Yes') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Yes") +
    theme_donut


p_backup <- plot_grid(p30,
                      plot_grid(p31, p32, p33, ncol = 3),
                      ncol = 2,
                      rel_widths = c(1.5, 2))

# Device Protection plot
df_protection <- df %>%
  group_by(DeviceProtection, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p34 <- ggplot(df_protection, aes(x = DeviceProtection, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('DeviceProtection') +
    theme_bar2

    
p35 <- df_protection %>%
  filter(DeviceProtection=='No') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No") +
    theme_donut

p36 <- df_protection %>%
  filter(DeviceProtection=='No internet service') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No internet service") +
    theme_donut

p37 <- df_protection %>%
  filter(DeviceProtection=='Yes') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Yes") +
    theme_donut


p_protection <- plot_grid(p34,
                          plot_grid(p35, p36, p37, ncol = 3),
                          ncol = 2,
                          rel_widths = c(1.5, 2))


plot_grid(p_security, p_backup, p_protection,
          get_legend(p26 + theme(legend.position='bottom')),
          ncol = 1)

```


```{r fig.width=10}
# Tech Support plot
df_support <- df %>%
  group_by(TechSupport, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p38 <- ggplot(df_support, aes(x = TechSupport, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('TechSupport') +
    theme_bar2

    
p39 <- df_support %>%
  filter(TechSupport=='No') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No") +
    theme_donut

p40 <- df_support %>%
  filter(TechSupport=='No internet service') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No internet service") +
    theme_donut

p41 <- df_support %>%
  filter(TechSupport=='Yes') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Yes") +
    theme_donut


p_support <- plot_grid(p38,
                       plot_grid(p39, p40, p41, ncol = 3),
                       ncol = 2,
                       rel_widths = c(1.5, 2))

# Streaming TV plot
df_tv <- df %>%
  group_by(StreamingTV, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p42 <- ggplot(df_tv, aes(x = StreamingTV, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('StreamingTV') +
    theme_bar2

    
p43 <- df_tv %>%
  filter(StreamingTV=='No') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No") +
    theme_donut

p44 <- df_tv %>%
  filter(StreamingTV=='No internet service') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No internet service") +
    theme_donut

p45 <- df_tv %>%
  filter(StreamingTV=='Yes') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Yes") +
    theme_donut


p_tv <- plot_grid(p42,
                  plot_grid(p43, p44, p45, ncol = 3),
                  ncol = 2,
                  rel_widths = c(1.5, 2))


# Streaming Movies plot
df_movies <- df %>%
  group_by(StreamingMovies, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p46 <- ggplot(df_movies, aes(x = StreamingMovies, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('StreamingMovies') +
    theme_bar2

    
p47 <- df_movies %>%
  filter(StreamingMovies=='No') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No") +
    theme_donut

p48 <- df_movies %>%
  filter(StreamingMovies=='No internet service') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No internet service") +
    theme_donut

p49 <- df_movies %>%
  filter(StreamingMovies=='Yes') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Yes") +
    theme_donut


p_movies <- plot_grid(p46,
                  plot_grid(p47, p48, p49, ncol = 3),
                  ncol = 2,
                  rel_widths = c(1.5, 2))

plot_grid(p_support, p_tv, p_movies,
          get_legend(p38 + theme(legend.position='bottom')),
          ncol = 1)
```


```{r fig.width=8}
# Contract plot
df_contract <- df %>%
  group_by(Contract, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p50 <- ggplot(df_contract, aes(x = Contract, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('Contract') +
    theme_bar2

    
p51 <- df_contract %>%
  filter(Contract=='Month-to-month') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Month-to-month") +
    theme_donut

p52 <- df_contract %>%
  filter(Contract=='One year') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("One year") +
    theme_donut

p53 <- df_contract %>%
  filter(Contract=='Two year') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Two year") +
    theme_donut


p_contract <- plot_grid(p50,
                        plot_grid(p51, p52, p53, ncol = 3),
                        ncol = 2,
                        rel_widths = c(1.75, 2))

# Paperless Billing plot
df_paperless <- df %>%
  group_by(PaperlessBilling, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p54 <- ggplot(df_paperless, aes(x = PaperlessBilling, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('PaperlessBilling') +
    theme_bar2

    
p55 <- df_paperless %>%
  filter(PaperlessBilling=='No') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("No") +
    theme_donut

p56 <- df_paperless %>%
  filter(PaperlessBilling=='Yes') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Yes") +
    theme_donut


p_paperless <- plot_grid(p54,
                         plot_grid(p55, p56, ncol = 3),
                         ncol = 2,
                         rel_widths = c(1.75, 2))

plot_grid(p_contract, p_paperless,
          get_legend(p50 + theme(legend.position='bottom')),
          ncol = 1)
```


```{r fig.width=10}
# Payment Method plot
df_payment <- df %>%
  group_by(PaymentMethod, Churn) %>%
  summarise(Count = n()) %>%
  mutate(Percent = prop.table(Count)*100)

p57 <- ggplot(df_payment, aes(x = PaymentMethod, y = Count, fill = Churn)) +
    geom_bar(stat='identity') +
    scale_fill_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle('PaperlessBilling') +
    theme_bar2 +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

p58 <- df_payment %>%
  filter(PaymentMethod=='Bank transfer (automatic)') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Bank transfer (automatic)") +
    theme_donut

p59 <- df_payment %>%
  filter(PaymentMethod=='Credit card (automatic)') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Credit card (automatic)") +
    theme_donut

p60 <- df_payment %>%
  filter(PaymentMethod=='Electronic check') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Electronic check") +
    theme_donut

p61 <- df_payment %>%
  filter(PaymentMethod=='Mailed check') %>%
  ggplot(aes(x = 2, y = Percent, fill = Churn)) +
    geom_col(fill = c('#F8766D', '#00BA38')) +
    geom_text(aes(x = 2, y = Percent, label = sprintf("%.2f%%", Percent)),
              position = position_stack(vjust = 0.5, reverse = TRUE),
              size = 3) +
    coord_polar('y') + xlim(.2, 2.5) +
    ggtitle("Mailed check") +
    theme_donut



plot_grid(plot_grid(p57,
                    plot_grid(p58, p59, p60, p61, ncol = 2),
                    ncol = 2,
                    rel_widths = c(1.5, 2)),
          get_legend(p57 + theme(legend.position='bottom')),
          ncol = 1)
```


```{r fig.width=8}
# Tenure distribution (histogram)
p62 <- ggplot(df, aes(x = tenure)) +
    geom_histogram(binwidth = 1, fill = '#F8766D') +
    xlab('Months') +
    ggtitle("Distribution of Tenure") +
    theme_bar

# Tenure Boxplot
p63 <- ggplot(df, aes(y = tenure, fill = Churn)) +
  geom_boxplot() +
  scale_fill_manual(values=c('#F8766D', '#00BA38')) +
  ggtitle("Customer Churn vs Tenure") +
  theme_bar +
  theme(axis.text.x = element_blank(),
        legend.position='bottom')

plot_grid(p62, p63, ncol=1)
```


```{r fig.width=8}
# Monthly Charges distribution (histogram)
p64 <- ggplot(df, aes(x = MonthlyCharges)) +
  geom_histogram(binwidth = 5, fill = '#F8766D') +
  xlab('Dollars (binwidth = 5)') +
  ggtitle("Monthly Charges Distribution") +
  theme_bar
  
# Monthly Charges Boxplot
p65 <- ggplot(df, aes(y = MonthlyCharges, fill = Churn)) +
  geom_boxplot() +
  scale_fill_manual(values=c('#F8766D', '#00BA38')) +
  ggtitle("Customer Churn vs Monthly Charges") +
  theme_bar +
  theme(axis.text.x = element_blank(),
        legend.position='bottom')
        
plot_grid(p64, p65, ncol=1)
```


```{r fig.width=8}
#Total Charges distribution (histogram)
p66 <- ggplot(df, aes(x = TotalCharges)) +
  geom_histogram(binwidth = 100, fill = '#F8766D') +
  xlab('Dollars (binwidth = 100)') +
  ggtitle("Total Charges Distribution") +
  theme_bar

# Total Charges Boxplot
p67 <- ggplot(df, aes(y = TotalCharges, fill = Churn)) +
  geom_boxplot() +
  scale_fill_manual(values=c('#F8766D', '#00BA38')) +
  ggtitle("Customer Churn vs Total Charges") +
  theme_bar +
  theme(axis.text.x = element_blank(),
        legend.position='bottom')

plot_grid(p66, p67, ncol=1)
```


```{r fig.width=8}
# Correlation of Contract vs Tenure
p68 <- df %>%
  filter(Contract=="Month-to-month") %>%
  ggplot(aes(x = tenure, color=Churn)) +
    geom_freqpoly(size = 2, binwidth = 1) +
    scale_color_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle("Month-to-month Contract vs Tenure") +
    xlab("Tenure (Months)") +
    theme_bar +
    theme(legend.position='right')

# Correlation of Contract vs Tenure
p69 <- df %>%
  filter(Contract=="One year") %>%
  ggplot(aes(x = tenure, color=Churn)) +
    geom_freqpoly(size = 2, binwidth = 1) +
    scale_color_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle("One-year Contract vs Tenure") +
    xlab("Tenure (Months)") +
    theme_bar +
    theme(legend.position='right')

# Correlation of Contract vs Tenure
p70 <- df %>%
  filter(Contract=="Two year") %>%
  ggplot(aes(x = tenure, color=Churn)) +
    geom_freqpoly(size = 2, binwidth = 1) +
    scale_color_manual(values=c('#F8766D', '#00BA38')) +
    ggtitle("Two-year Contract vs Tenure") +
    xlab("Tenure (Months)") +
    theme_bar +
    theme(legend.position='right')

plot_grid(p68, p69, p70, ncol=1)
```


```{r}
# Correlation between Continuous Variables
df %>%
  select(tenure, MonthlyCharges, TotalCharges) %>%
  drop_na() %>%
  cor() %>%
  ggcorrplot(title = "Correlation") +
  theme_bar2 +
  theme(axis.title.y = element_blank(), legend.position='right')

```


```{r}
df %>%
  select(tenure, MonthlyCharges, TotalCharges) %>%
  drop_na() %>%
  ggplot(aes(MonthlyCharges, TotalCharges)) +
  geom_point(colour = "#F8766D") +
  ggtitle("Monthly Charge vs Total Charge") +
  theme_bar
```

```{r fig.width=8}
# Correlation of Customer Subscription vs Monthly Charge
p71 <- ggplot(subset(df,
                     PhoneService %in% c("Yes")
                     & InternetService %in% c("DSL"," Fiber optic")),
       aes(x = MonthlyCharges, fill = Churn)) +
  geom_histogram(binwidth = 1) +
  ggtitle('Customer Subscription vs Monthly Charge') +
  ylab('Phone Service\n& Internet Service') +
  theme_bar +
  theme(legend.position='right')

# Correlation of Customer Subscription vs Monthly Charge
p72 <- ggplot(subset(df,
                     PhoneService %in% c("Yes")
                     & InternetService %in% c("DSL"," Fiber optic")),
       aes(x = MonthlyCharges, fill = Churn)) +
  geom_histogram(binwidth = 1) +
  ylab('Phone Service') +
  theme_bar +
  theme(legend.position='right')

# Correlation of Customer Subscription vs Monthly Charge
p73 <- ggplot(subset(df,
                     PhoneService %in% c("Yes")
                     & InternetService %in% c("DSL"," Fiber optic")),
       aes(x = MonthlyCharges, fill = Churn)) +
  geom_histogram(binwidth = 1) +
  ylab('Internet Service') +
  theme_bar +
  theme(legend.position='right')

plot_grid(p71, p72, p73, ncol=1)

```





